### ISSUE TITLE
at MikroBILL.Core_Base.MyWebClient.DownloadMyString(String URL, Int32 Timeout)

### ISSUE THREAD

**Issue by toxi22** [koduarve/mikrobill#4]
При попытке подключиться к серверу через MikroBill Remote.

```
8/30/2024 10:32:02PM || -------------
8/30/2024 10:32:02PM || MikroBILL v.2.0.13.0 at 8/29/2024 5:31:16PM started! [SVC x64]
8/30/2024 10:32:02PM || Available free physical memory: 960MB.
8/30/2024 10:32:02PM || Loaded file = /var/MikroBILL/MikroBILL.xml
8/30/2024 10:32:03PM || MikroREMOTE port set to: 7402
8/30/2024 10:32:04PM || Data restored from DB!
8/30/2024 10:32:04PM || Users: 0, Tariffs: 1, Groups: 0
8/30/2024 10:32:04PM || Readed 0 plugins from '/var/MikroBILL/Plugins/'.
8/30/2024 10:32:05PM || 
Check default HTTP host error! Now set: http://localhost/
Check host or update WEB files!The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at MikroBILL.Core_Base.MyWebClient.DownloadMyString(String URL, Int32 Timeout) in t:\MT_BILL_NEW_2.0.13\MT_Bill_Unix\MT_BILL_Unix\Core_Base.vb:line 1304
   at MikroBILL.BG_Class.CheckApacheVersion() in t:\MT_BILL_NEW_2.0.13\MT_Bill_Unix\MT_BILL_Unix\BG_Class.vb:line 1067
8/30/2024 10:33:04PM || Could not find a part of the path '/var/MikroBILL/Backup'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at MikroBILL.NewWeb.Config_LogsBackupsUpdates(List`1& SQL_A) in t:\MT_BILL_NEW_2.0.13\MT_Bill_Unix\MT_BILL_Unix\NewWeb.vb:line 6157
```

**Comment by toxi22** [comment]
Возможно кому-то поможет.
Скачал последнюю бета-версию MikroBILL на сервер и на клиента, чтобы была одинаковая версия софта.
Установил старую версию dotnet на сервер:
```
wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
chmod +x ./dotnet-install.sh
./dotnet-install.sh --channel 6.0
```
И наконец-то MikroBILL Remote законектилось с сервером.

Причем, никаких ошибок не писало о том, что версия сервера и версия клиента - разные. Возможно, нужно будет добавить такую информацию?
